import './style/style.scss'
export { default as Icon} from './Icon'
export { default as Avatar } from './Avatar'
export { default as BackTop } from './Backtop'
export { default as Button} from './Button'
export { default as Loading} from './Loading'
export { default as Divider} from './Divider'